steps:
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: ib23-d052537-pirapi
    integrationFlowId: ConsumeEventsFromS4HANACloudwitoutslack
    integrationFlowName: ConsumeEventsFromS4HANACloudwitoutslack
    packageId: 01cicdpiper
    filePath: ConsumeEventsFromS4HANACloudwitoutslack.zip

  integrationArtifactUpdateConfiguration:
    cpiApiServiceKeyCredentialsId: ib23-d052537-pirapi
    integrationFlowId: ConsumeEventsFromS4HANACloudwitoutslack
    integrationFlowVersion: 1.0.16
    parameterKey: s4cloudcred
    parameterValue: xyz
    
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: ib23-d052537-pirapi
    integrationFlowId: ConsumeEventsFromS4HANACloudwitoutslack
    
  integrationArtifactGetMplStatus:
    cpiApiServiceKeyCredentialsId: ib23-d052537-pirapi
    integrationFlowId: ConsumeEventsFromS4HANACloudwitoutslack
    
    
  integrationArtifactGetServiceEndpoint:
    cpiApiServiceKeyCredentialsId: ib23-d052537-pirapi
    integrationFlowId: ConsumeEventsFromS4HANACloudwitoutslack
    
