steps:
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: ib23-d052537-pirapi
    integrationFlowId: ConsumeEventsFromS4HANACloudwitoutslaccicdtests
    integrationFlowName: ConsumeEventsFromS4HANACloudwitoutslaccicdtests
    packageId: CICD
    filePath: ConsumeEventsFromS4HANACloudwitoutslaccicdtests.zip

  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: ib23-d052537-pirapi
    integrationFlowId: ConsumeEventsFromS4HANACloudwitoutslaccicdtests
