steps:
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: ib23-d052537-pirapi
    integrationFlowId: ConsumeEventsFromS4HANACloudwitoutslaccicdtest
    integrationFlowName: ConsumeEventsFromS4HANACloudwitoutslaccicdtests
    packageId: 00cicdservice
    filePath: ConsumeEventsFromS4HANACloudwitoutslaccicdtest.zip
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: ib23-d052537-pirapi
    integrationFlowId: DelayedDelivery_Process
  integrationArtifactGetMplStatus:
    cpiApiServiceKeyCredentialsId: ib23-d052537-pirapi
    integrationFlowId: ConsumeEventsFromS4HANACloudwitoutslaccicdtest
  integrationArtifactGetServiceEndpoint:
    cpiApiServiceKeyCredentialsId: ib23-d052537-pirapi
    integrationFlowId: ConsumeEventsFromS4HANACloudwitoutslaccicdtest